=head1 NAME

aa_monitor - Flexible service health checking framework

=head1 DESCRIPTION

aa_monitor is framework consisting of:

 * core library
 * service checking modules (currently: 40)
 * standalone http, https, fastcgi daemon
 * command line client
 * nagios plugin

=head1 TODO

WRITE END-USER DOCUMENTATION!

=head1 GETTING STARTED

aa_monitor comes with only one command: B<aa_monitor> which handles all usage scenarios.

=head2 STANDALONE HTTP DAEMON

Invoke:

 ./bin/aa_monitor --daemon

Open web browser and go to: L<http://localhost:1552>

=head2 COMMAND LINE CLIENT

Invoke fsusage check:

 ./bin/aa_monitor -e module=FSUsage usage_threshold=50

=head2 NAGIOS PLUGIN

Invoke fsusage check:

 ./bin/aa_monitor -N module=FSUsage usage_threshold=50

=head1 LIST OF CURRENTLY IMPLEMENTED MODULES:
 
 * AsProxy
 * CertificateDB
 * DBI
 * DBIReplication
 * DHCP
 * DNS
 * DNSCompare
 * DNSZone
 * DNSZoneConsistency
 * DRBD
 * EDAC
 * FSUsage
 * FTP
 * HPRAID
 * IntelSensors
 * JSON
 * Jabber
 * KIS
 * Kerberos
 * LDAP
 * LVS
 * MDRAID
 * Mail
 * MegaRAID
 * MegaSAS
 * Memcached
 * MemcachedRepl
 * MongoDB
 * MongoDBReplicaSet
 * Mount
 * MySQLNDB
 * MySQLNDBUsage
 * Process
 * Rsync
 * SMART
 * TCPSocket
 * Time
 * URL
 * XML

=head1 CREDITS

See CREDITS file.

=cut
