=head1 RATIONALE

We're just dwarfs standing on the shoulders of giants.

=head1 BUNDLED SOFTWARE

This software bundles the following third-party party libraries for the sake
of easy deployment:

=head2 JSON

L<JSON> version 2.50 by Makamaka Hannyaharamitu

 * JSON 2.50 by Makamaka Hannyaharamitu
	http://search.cpan.org/~makamaka/JSON-2.50/lib/JSON.pm
	License: Perl artistic license and GPL

=head2 Pod::Simple

 * Pod::Simple 3.15 by David E. Wheeler
   http://search.cpan.org/~dwheeler/Pod-Simple-3.15/lib/Pod/Simple.pod
   License: Perl artistic license

=head2 Text::ParseWords
 
 * Text::ParseWords 3.27 by Alexandr Ciornii
   http://search.cpan.org/~chorny/Text-ParseWords-3.27/ParseWords.pm
   License: Perl (Artistic and GPL)

=head2 Plack::Handler::FCGI::PP

 * modified version of Plack::Handler::FCGI::PP by Christian Hansen and Tatsuhiko Miyagawa
   https://github.com/miyagawa/Plack/blob/master/lib/Plack/Handler/Net/FastCGI.pm
   License: Perl artistic license

=head1 CONTRIBUTORS

=head3 Uros Golja

Uros has created or contributed to the following modules:

 * SMART
 * FSUsage
 * Process
 * MySQLNDBUsage
 * KIS

=cut
